# Generated by Django 5.2.5 on 2025-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=18, unique=True, verbose_name='MAC')),
                ('gponsn', models.CharField(max_length=12, unique=True, verbose_name='SN')),
                ('ssid', models.CharField(max_length=10, verbose_name='SSID')),
                ('psk', models.CharField(max_length=16, verbose_name='PSK')),
                ('userpass', models.CharField(max_length=16, verbose_name='UserPwd')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
                ('tr069', models.CharField(blank=True, default='', max_length=128, verbose_name='TR069')),
                ('haswifi', models.IntegerField(verbose_name='WiFi')),
                ('province', models.CharField(blank=True, default='', max_length=16, verbose_name='Province')),
            ],
        ),
    ]
