# Generated by Django 5.2.5 on 2025-09-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='Record',
        ),
    ]
