# Generated by Django 5.2.5 on 2025-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_web', '0002_rename_device_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=18, unique=True, verbose_name='MAC')),
                ('gponsn', models.CharField(max_length=12, unique=True, verbose_name='SN')),
                ('status', models.IntegerField(verbose_name='Status')),
                ('pluginList', models.CharField(max_length=128, verbose_name='Plugin')),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='tr069',
        ),
    ]
