# Generated by Django 5.2.5 on 2025-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_web', '0003_device_remove_record_tr069'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='pluginList',
            field=models.JSONField(default=dict, verbose_name='Plugins'),
        ),
    ]
