# Generated by Django 5.2.5 on 2025-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_web', '0004_alter_device_pluginlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tr069',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='TR069'),
        ),
    ]
