# Generated by Django 5.2.5 on 2025-09-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_web', '0005_device_tr069'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='shortconn',
            field=models.BooleanField(blank=True, default=True, max_length=16, verbose_name='Short Connection'),
        ),
    ]
