# Generated by Django 5.2.5 on 2025-09-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_web', '0006_record_shortconn'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='heartbeat',
            field=models.IntegerField(blank=True, default=120, max_length=16, verbose_name='Heartbeat'),
        ),
        migrations.AlterField(
            model_name='device',
            name='pluginList',
            field=models.JSONField(blank=True, default=dict, verbose_name='Plugins'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.IntegerField(blank=True, default=0, verbose_name='Status'),
        ),
    ]
