# Generated by Django 5.2.5 on 2025-09-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_web', '0007_record_heartbeat_alter_device_pluginlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='heartbeat',
            field=models.IntegerField(blank=True, default=120, verbose_name='Heartbeat'),
        ),
    ]
