# Generated by Django 5.2.5 on 2025-09-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_web', '0008_alter_record_heartbeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='psk',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='PSK'),
        ),
        migrations.AlterField(
            model_name='record',
            name='ssid',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='SSID'),
        ),
    ]
