# Generated by Django 5.2.5 on 2025-09-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_web', '0009_alter_record_psk_alter_record_ssid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='pluginList',
            field=models.JSONField(blank=True, default=list, verbose_name='Plugins'),
        ),
    ]
