# Generated by Django 5.2.5 on 2025-09-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_web', '0010_alter_device_pluginlist'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['mac', 'gponsn'], name='bms_web_rec_mac_ef1f24_idx'),
        ),
    ]
